{{- if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
    name: {{ template "tls-secret" . }}
spec:
    dnsNames:
      {{- range .Values.tls.hosts }}
      - {{ . | quote }}
      {{- end }}
    issuerRef:
        group: {{ .Values.tls.group }}
        kind: {{ .Values.tls.kind }}
        name: {{ .Values.tls.issuer }}
    secretName: {{ template "tls-secret" . }}
{{- end }}