apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ template "pvc" . }}
spec:
    accessModes:
        - {{ .Values.persistence.accessMode }}
    resources:
        requests:
            storage: {{ .Values.persistence.storage }}